asn1crt: add missing prototypes for (De|En)codeOctetString_fragmentation
In e93c052aa208 ("support for OCTET STRING (CONTAINING Other-Type)"),
BitStream_EncodeOctetString_fragmentation() and
BitStream_DecodeOctetString_fragmentation() were added, but no
prototypes were added.

When compiling the generated ASN.1 encoders and decoders with g++, the
following error is reported:

"""
error: no previous declaration for ‘flag BitStream_EncodeOctetString_fragmentation(i3ds_asn1::BitStream*, const byte*, int)’
[-Werror=missing-declarations]
flag BitStream_EncodeOctetString_fragmentation(BitStream* pBitStrm, const byte* arr, int nCount) {

compilation terminated due to -Wfatal-errors.
"""